#########################
# Database network conf #
#########################
DB_IP = "127.0.0.1"
DB_PORT = 27017

###################
# Documents names #
###################
USERS_DOCUMENT = "users"
EVALUATORS_DOCUMENT = "evaluators"
CANDIDATES_DOCUMENT = "candidates"
GROUPS_DOCUMENT = "groups"
ASSIGNMENTS_DOCUMENT = "assignments"
ASSIGNMENT_SUBMISSIONS_DOCUMENT = "assignments_sub"

####################
#   Fields names   #
####################
# USERS / EVALUATORS / CANDIDATES #
# Generals
MAIL_FIELD = "email"
NAME_FIELD = "firstname"
LASTNAME_FIELD = "lastname"
PASSWORD_FIELD = "password"
CONFIRMED_FIELD = "confirmed"
TYPE_FIELD = "type"
EVALUATOR_TYPE = 'evaluator'
CANDIDATE_TYPE = 'candidate'
CREATED_TIMESTAMP = 'created_timestamp'

# Evaluators & candidates #
USER_ID_FIELD = 'user_id'
ORGANISATION_FIELD = 'organisation'

# Candidates #
CANDIDATES_GROUPS_FIELD = 'groups'

# Evaluator #
EVALUATOR_GROUPS_FIELD = 'groupsInCharge'
EVALUATOR_ASSIGNMENTS_FIELD = 'assignmentsCreated'
EVALUATOR_CORRECTED_PROGRAM_LEFT_NAME = 'corrected_programs_left'

# GROUPS #
GROUPS_ID_EVAL_FIELD = 'id_eval'
GROUPS_NAME_FIELD = 'name'
GROUPS_ASSIGNMENTS_IDS_FIELD = 'assignments_ids'
GROUPS_CANDIDATES_IDS_FIELD = 'candidates_ids'
GROUPS_ASSIGNMENTS_FIELD = 'assignments'
GROUPS_ASSIGNMENTS_DEADLINE = 'deadline'
GROUPS_ASSIGNMENTS_SUB_ID = 'submissions_ids'
GROUPS_ASSIGNMENT_TEMPLATE = {
    GROUPS_ASSIGNMENTS_IDS_FIELD: None,
    GROUPS_ASSIGNMENTS_DEADLINE: None,
    GROUPS_ASSIGNMENTS_SUB_ID: []
}


# Assignments #
ASSIGNMENT_NAME = 'name'
ASSIGNMENT_FILENAME = 'filename'
ASSIGNMENT_AUTHOR_ID = 'author_id'
ASSIGNMENT_DESCRIPTION = 'description'
ASSIGNMENT_DEADLINE = 'deadline'
ASSIGNMENT_IS_VALID = 'is_valid'
ASSIGNMENT_INPUT_OUTPUTS = 'ios'
ASSIGNMENT_STATISTICS_NAME = 'stats'
ASSIGNMENT_STAT_TIME = 'cpu_time'
ASSIGNMENT_FILE_SIZE = 'file_size'
ASSIGNMENT_MEMORY_USED = 'memory_used'
ASSIGNMENT_MARKING_SCHEME_NAME = 'marking_scheme'
ASSIGNMENT_SUCCESS_IOS = 'success_ios'

ASSIGNMENT_MARKING_SCHEME = {
    ASSIGNMENT_FILE_SIZE: 0.0,
    ASSIGNMENT_STAT_TIME: 0.0,
    ASSIGNMENT_MEMORY_USED: 0.0
}
ASSIGNMENT_STATISTICS = {
    ASSIGNMENT_STAT_TIME: None,
    ASSIGNMENT_FILE_SIZE: None,
    ASSIGNMENT_MEMORY_USED: None,
}

# ASSIGNMENT SUBMISSION #
ASSIGNMENT_SUB_DATE_TIME_STAMP = 'date_subm'
ASSIGNMENT_SUB_GRADE = 'grade'
ASSIGNMENT_SUB_CAND_ID = 'cand_id'
ASSIGNMENT_SUB_ASSIGN_ID = 'assignment_id'
ASSIGNMENT_SUB_GROUP_ID = 'group_id'


# Templates to fill
EVALUATORS_ITEM_TEMPLATE = {
    USER_ID_FIELD: "",
    ORGANISATION_FIELD: "",
    EVALUATOR_CORRECTED_PROGRAM_LEFT_NAME: 1000,
    EVALUATOR_GROUPS_FIELD: [],
    EVALUATOR_ASSIGNMENTS_FIELD: [],

}

CANDIDATES_ITEM_TEMPLATE = {
    USER_ID_FIELD: '',
    ORGANISATION_FIELD: '',
    CANDIDATES_GROUPS_FIELD: []
}

USERS_ITEM_TEMPLATE = {
    NAME_FIELD: "",
    LASTNAME_FIELD: "",
    PASSWORD_FIELD: "",
    MAIL_FIELD: "",
    CONFIRMED_FIELD: False,
    TYPE_FIELD: "",
    CREATED_TIMESTAMP: None
}

GROUP_TEMPLATE = {
    GROUPS_ID_EVAL_FIELD: '',
    GROUPS_NAME_FIELD: '',
    GROUPS_ASSIGNMENTS_FIELD: [],
    GROUPS_CANDIDATES_IDS_FIELD: [],
    CREATED_TIMESTAMP: None
}


ASSIGNMENT_ITEM_TEMPLATE = {
    ASSIGNMENT_NAME: '',
    ASSIGNMENT_FILENAME: '',
    ASSIGNMENT_AUTHOR_ID: '',
    ASSIGNMENT_DESCRIPTION: '',
    ASSIGNMENT_IS_VALID: -1,
    ASSIGNMENT_INPUT_OUTPUTS: [],
    ASSIGNMENT_STATISTICS_NAME: ASSIGNMENT_STATISTICS,
    CREATED_TIMESTAMP: None

}

CANDIDATE_ASSIGNMENT_SUBMISSION_TEMPLATE = {
    ASSIGNMENT_SUB_CAND_ID: '',
    ASSIGNMENT_SUB_ASSIGN_ID: '',
    ASSIGNMENT_SUB_GROUP_ID: '',
    ASSIGNMENT_FILENAME: '',
    ASSIGNMENT_IS_VALID: 1,
    ASSIGNMENT_SUB_DATE_TIME_STAMP: 0,
    ASSIGNMENT_STATISTICS_NAME: ASSIGNMENT_STATISTICS,
    ASSIGNMENT_SUB_GRADE: None,
    CREATED_TIMESTAMP: None
}
